### ISSUE TITLE
Multi-display support

### ISSUE THREAD

**Issue by lesderid** [lesderid/keynavish#2]
keynavish was not developed with multi-display support in mind.

A good start would be to figure out to what extent it's broken on systems with more than one display, and make a list of what needs to be fixed.

**Comment by tshirtman** [comment]
Forgive me if this is too obvious but:
- It starts on the main windows display, not the one which currently has the cursor.
- Moving is limited to the screen it was started from

On the other hand, keynav itself starts on the screen currently having the cursor, and allows moving the grid to other displays by moving in their direction.
It would be nice to at least allow moving through screen borders to the next screen in that direction.

Aside that it seems to work decently.

**Comment by lesderid** [comment]
I hope to get this done soon.
